### ISSUE TITLE
SPIFFS

### ISSUE THREAD

**Issue by auriel-cardoso** [ProyectoConsola/notas#3]
SPIFFS es un sistema de archivos usado para la comunicación de datos por SPI entre el microcontrolador y una memoria Flash, es necesario investigar el concepto y agregarlo en las notas.

**Comment by GuilleDevMX** [comment]
Se subió una investigación sencilla de spiffs

[Documentación sencila de spiffs](https://github.com/ProyectoConsola/notas/blob/main/spiffs.md)
